language: python
services: docker
env:
  global:
  - ROLE_NAME: haya-monitoring
install:
- pip install molecule docker
- chmod +x docker-playbook-test.sh
before_script:
- cd ../
- mv ansible-role-$ROLE_NAME $ROLE_NAME
- cd $ROLE_NAME
- ./docker-playbook-test.sh
script:
- molecule test
