---
- name: Install prometheus
  include_tasks: "prometheus-stack/prometheus.yml"
  when: haya_monitoring_install_prometheus|bool

- name: Install node-exporter
  include_tasks: "prometheus-stack/exporter.yml"
  when: haya_monitoring_install_exporter|bool

- name: Install push-gateway
  include_tasks: "prometheus-stack/gateway.yml"
  when: haya_monitoring_install_gateway|bool

- name: Install cadvisor
  include_tasks: "prometheus-stack/cadvisor.yml"
  when: haya_monitoring_install_cadvisor|bool

- name: Install grafana
  include_tasks: "prometheus-stack/grafana.yml"
  when: haya_monitoring_install_grafana|bool

- name: Install alertmanager
  include_tasks: "prometheus-stack/alertmanager.yml"
  when: haya_monitoring_install_alertmanager|bool

- name: Install prometheus-bot
  include_tasks: "prometheus-stack/prometheus-tg-bot.yml"
  when: haya_monitoring_install_prometheus-tg-bot|bool