---
- name: restart alertmanager
  docker_container:
    name: "alertmanager"
    restart: true

- name: restart prometheus-tg-bot
  docker_container:
    name: "prometheus-bot"
    restart: true

- name: restart graylog
  docker_compose:
    project_name: "graylog"
    project_src: "/opt/graylog"
    restarted: yes
