---
- name: Launch grafana prometheus
  become: true
  docker_container:
    image: grafana/grafana:{{ haya_monitoring_grafana_version }}
    env:
      GF_SECURITY_ADMIN_USER: "{{ haya_monitoring_grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ haya_monitoring_grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    name: grafana
    detach: true
    privileged: true
    published_ports:
      - "0.0.0.0:{{ haya_monitoring_grafana_port }}:3000"
    restart_policy: always
    state: started
    volumes:
      - "{{ haya_monitoring_grafana_data }}:/var/lib/grafana"
      - "{{ haya_monitoring_grafana_config_path }}/datasources:/etc/grafana/datasources"
      - "{{ haya_monitoring_grafana_config_path }}/dashboards:/etc/grafana/dashboards"
