version: '2'
services:
  mongodb:
    image: mongo:3
    volumes:
      - mongo_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
    network_mode: "host"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
    network_mode: "host"

  graylog:
    image: daocasino/graylog:latest
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      - /etc/graylog/graylog.conf:/usr/share/graylog/data/config/graylog.conf:ro
    depends_on:
      - mongodb
      - elasticsearch
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
